### ISSUE TITLE
Improve the documentation to cover all methods

### ISSUE THREAD

**Issue by bmds** [cartridge/cartridge-module-util#3]
The documentation currently doesn't cover all methods.

Each should have a description and at least one example

**Comment by furzeface** [comment]
:octocat:

**Comment by tawashley** [comment]
I've check the documentation that currently exists, and all 15 public functions are documented in the README. Considering the date this issue was raised, going to considering this issue as fixed and close it.

If these isn't the case, a new issue can be raised.
